travis:
  secure:
    BINSTAR_TOKEN: ei36MOq0ckOawJpJENohMkAARHozP7bEuen4VstPoyjBHplM2nnV402xyrtWRsKR6SDg8DhlqFAoIpNpbfUuNYa550we3oWmzWr2oQ6kg1/mVpX+b+mp0wQpbp4kLvip9lX8wo4bKEyFhND0KmzYnVABATMLySg/239Z1vGI7i55N94ZzK7H9SXsKY58s3v3co0nNrTVpoa5aJPN6JBe+9CfWx4BZpE/xw4Fx6YwveVC2yoSMLm03BtevOmEv8lGwEFMQYRrZ/Vm2exxzOnj0WlHJJAb0lZXFfTpEb+oD7yJBgh1jweGlt8LQXI9Bf1H9ex077admj/TgaA3SHtdQVwJ5at27YvV6IHMdTORsRPE9xZ2RETZuX11wz3+A6nekf9G4I6BaodO7DnreLl20K4Pr9ZHnjvwRQrz11eZ0zxaesE9hQWwbI39AwCQwXK7A2pE31r12kqwUfT0OCclzUYxIDAHY42UvAn7cYWc57xJn+/B/qaj142gQ77GkknsKE6EnatEdMvQyQHAWY0W65AIO7uCmhm3jTaTceDLsRtjY+vnn+n27TqUJWdCu0J+aRGNGOFlxDsEQo+ky/lFII6PZ3HtCZbCsKDN/1fxq9cZqBe6/C28ujd1EprIdIPcZgohcdS++MaBTUwUGkkgcfT5p2MA6Ii7zSdPnQ2ulpA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
