travis:
  secure:
    BINSTAR_TOKEN: I18aBRrkymeuqY6rf6YCAnBPaC2tGJcsqz1ehxmdoOMX+HK46bnIAAH+p2QiCTTh5YmYgfmSXj+SoS+P6p0JT5dNIlufpWswZ9L6cp1C+lHov8NK5XfVXa+e7DTw/ZuUbD/hclCnTemnBZyLuegR1IKJZH5eXfJWpv5XmERb4bAUEmMMGjS2/QtlcnN6TXPBLIEc2MSRS2TXodmYEqP6xRTMugaCn7wlgUQOeLxPW9H9hWzKWQkLxkMrPPJVKS9fhEk+H9srGu8JEHOJdfFfm8BmA+yRUYR4X60rYywj+w5ye9vAeQNDK8/Re5bXGJxAvAWCCSIqEcDhR+n55sR0L4ZgA9i+rto4MQqWP5sjyw0OGx+7/tLups7JOsujI4bdO+2wRc8k21SH3xbiIUeItnDMtSbClnpXrGY99o8VIZowm/dVAu2tym8AlUrM3vKIWAOC/qdcLIE+GE598lDc2QedMnKNYW82AozO4h00gzSp2oxykcjWJyM6Z3D/4mPF0JaMnfK08Gj9b3Wlar3RxYqFwmmPwFs/5Ogx2rnfrN5le73Hk+vEfSZ+7Gy4WFDsaQMaC6QEjrssdTUEin/X5Ja0/H/Nnpt/c5lg3208Vpn/a/EGMg8TUZHssVD7WSkIfTS5G0VAmvijojBALjpD7Iar3JSohgPpfFjkNxYZGgM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
